// TODO: replace with the correct allocation wallets
module.exports = {
  namedAccounts: {
    deployer: {
      default: 0,
      1: process.env.DEPLOYER_WALLET, // ETHEREUM MAINNET
      5: process.env.TEST_DEPLOYER_WALLET, // GOERLI TESTNET
      56: process.env.DEPLOYER_WALLET, //BNB
      97: process.env.TEST_DEPLOYER_WALLET, //BNB TESTNET
      137: process.env.DEPLOYER_WALLET, //POLYGON MAINNET
      80001: process.env.TEST_DEPLOYER_WALLET, //POLYGON TESTNET
    },
    LAUNCHPAD_PUBLIC_SALE_WALLET: {
      default: 1,
      1: process.env.LAUNCHPAD_PUBLIC_SALE_WALLET, // ETHEREUM MAINNET
      5: process.env.TEST_LAUNCHPAD_PUBLIC_SALE_WALLET, // GOERLI TESTNET
      56: process.env.LAUNCHPAD_PUBLIC_SALE_WALLET, // BNB MAINNET
      97: process.env.TEST_LAUNCHPAD_PUBLIC_SALE_WALLET, //BNB TESTNET
      137: process.env.LAUNCHPAD_PUBLIC_SALE_WALLET, //POLYGON MAINNET
      80001: process.env.TEST_LAUNCHPAD_PUBLIC_SALE_WALLET, //POLYGON TESTNET
    },
    LIQUIDITY_POOL_WALLET: {
      default: 2,
      1: process.env.LIQUIDITY_POOL_WALLET, // ETHEREUM MAINNET
      5: process.env.TEST_LIQUIDITY_POOL_WALLET, // GOERLI TESTNET
      56: process.env.LIQUIDITY_POOL_WALLET, // BNB MAINNET
      97: process.env.TEST_LIQUIDITY_POOL_WALLET, //BNB TESTNET
      137: process.env.LIQUIDITY_POOL_WALLET, //POLYGON MAINNET
      80001: process.env.TEST_LIQUIDITY_POOL_WALLET, //POLYGON TESTNET
    },
    EARLY_CONTRIBUTOR_POOL_WALLET: {
      default: 3,
      1: process.env.EARLY_CONTRIBUTOR_POOL_WALLET, // ETHEREUM MAINNET
      5: process.env.TEST_EARLY_CONTRIBUTOR_POOL_WALLET, // GOERLI TESTNET
      56: process.env.EARLY_CONTRIBUTOR_POOL_WALLET, // BNB MAINNET
      97: process.env.TEST_EARLY_CONTRIBUTOR_POOL_WALLET, //BNB TESTNET
      137: process.env.EARLY_CONTRIBUTOR_POOL_WALLET, //POLYGON MAINNET
      80001: process.env.TEST_EARLY_CONTRIBUTOR_POOL_WALLET, //POLYGON TESTNET
    },
    ECOSYSTEM_FUND_WALLET: {
      default: 4,
      1: process.env.ECOSYSTEM_FUND_WALLET, // ETHEREUM MAINNET
      5: process.env.TEST_ECOSYSTEM_FUND_WALLET, // GOERLI TESTNET
      56: process.env.ECOSYSTEM_FUND_WALLET, // BNB MAINNET
      97: process.env.TEST_ECOSYSTEM_FUND_WALLET, //BNB TESTNET
      137: process.env.ECOSYSTEM_FUND_WALLET, //POLYGON MAINNET
      80001: process.env.TEST_ECOSYSTEM_FUND_WALLET, //POLYGON TESTNET
    },
    TREASURY_WALLET: {
      default: 5,
      1: process.env.TREASURY_WALLET, // ETHEREUM MAINNET
      5: process.env.TEST_TREASURY_WALLET, // GOERLI TESTNET
      56: process.env.TREASURY_WALLET, // BNB MAINNET
      97: process.env.TEST_TREASURY_WALLET, //BNB TESTNET
      137: process.env.TREASURY_WALLET, //POLYGON MAINNET
      80001: process.env.TEST_TREASURY_WALLET, //POLYGON TESTNET
    },
    STRATEGIC_INVESTORS_WALLET: {
      default: 6,
      1: process.env.STRATEGIC_INVESTORS_WALLET, // ETHEREUM MAINNET
      5: process.env.TEST_STRATEGIC_INVESTORS_WALLET, // GOERLI TESTNET
      56: process.env.STRATEGIC_INVESTORS_WALLET, // BNB MAINNET
      97: process.env.TEST_STRATEGIC_INVESTORS_WALLET, //BNB TESTNET
      137: process.env.STRATEGIC_INVESTORS_WALLET, //POLYGON MAINNET
      80001: process.env.TEST_STRATEGIC_INVESTORS_WALLET, //POLYGON TESTNET
    },
    ADVISORS_WALLET: {
      default: 7,
      1: process.env.ADVISORS_WALLET, // ETHEREUM MAINNET
      5: process.env.TEST_ADVISORS_WALLET, // GOERLI TESTNET
      56: process.env.ADVISORS_WALLET, // BNB MAINNET
      97: process.env.TEST_ADVISORS_WALLET, //BNB TESTNET
      137: process.env.ADVISORS_WALLET, //POLYGON MAINNET
      80001: process.env.TEST_ADVISORS_WALLET, //POLYGON TESTNET
    },
    MARKETING_WALLET: {
      default: 8,
      1: process.env.MARKETING_WALLET, // ETHEREUM MAINNET
      5: process.env.TEST_MARKETING_WALLET, // GOERLI TESTNET
      56: process.env.MARKETING_WALLET, // BNB MAINNET
      97: process.env.TEST_MARKETING_WALLET, //BNB TESTNET
      137: process.env.MARKETING_WALLET, //POLYGON MAINNET
      80001: process.env.TEST_MARKETING_WALLET, //POLYGON TESTNET
    },
    TEAM_WALLET: {
      default: 9,
      1: process.env.TEAM_WALLET, // ETHEREUM MAINNET
      5: process.env.TEST_TEAM_WALLET, // GOERLI TESTNET
      56: process.env.TEAM_WALLET, // BNB MAINNET
      97: process.env.TEST_TEAM_WALLET, //BNB TESTNET
      137: process.env.TEAM_WALLET, //POLYGON MAINNET
      80001: process.env.TEST_TEAM_WALLET, //POLYGON TESTNET
    },
  },
}

